#include "pwm.h"

#define GPIO_MODER_ALTARNATE 2
#define TIM_CCMR1_PWM_MODE_1 6
#define TIM_CCMR1_CC1S_OUTPUT 0

void pwm_init(void){
	//Alternate mode for GPIO
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER |= (GPIO_MODER_ALTARNATE << GPIO_MODER_MODE7_Pos) | (GPIO_MODER_ALTARNATE << GPIO_MODER_MODE8_Pos);
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL7_0;
	GPIOA->AFR[1] |= GPIO_AFRH_AFRH0_0;
	//Set TIM1 parameters 
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	TIM1->PSC = 0;
	TIM1->ARR = 10000; // 50 Hz
	TIM1->CCR1 = 5000;
	TIM1->CCMR1 |= (0 << TIM_CCMR1_CC1S_Pos) | (TIM_CCMR1_PWM_MODE_1 << TIM_CCMR1_OC1M_Pos);
	TIM1->CCER |= TIM_CCER_CC1E | TIM_CCER_CC1NE;
	TIM1->BDTR |= TIM_BDTR_MOE | 12 | 6 << 5; // 3.5 us
	TIM1->CR1 |= TIM_CR1_CEN;
}